
export const HomeNavigationUils = [
    {
        title: 'For My Business',
        path: '/'
    },
    {
        title: 'For Me',
        path: '/'
    },
    {
        title: 'VT Apps Market',
        path: '/'
    },
]

export const organizationData = [
    { icon: 'https://oneid.veevotech.com/org_dp/files/10467752-default.jpeg', name: 'XYZ Badar', type: 'IT/Software Services' },
    { icon: 'https://oneid.veevotech.com/org_dp/files/10467752-default.jpeg', name: 'XYZ Badar', type: 'IT/Software Services' },
    { icon: 'https://oneid.veevotech.com/org_dp/files/10467752-default.jpeg', name: 'XYZ Badar', type: 'IT/Software Services' },
    { icon: 'https://oneid.veevotech.com/org_dp/files/10467752-default.jpeg', name: 'XYZ Badar', type: 'IT/Software Services' },
    { icon: 'https://oneid.veevotech.com/org_dp/files/10467752-default.jpeg', name: 'XYZ Badar', type: 'IT/Software Services' },
    { icon: 'https://oneid.veevotech.com/org_dp/files/10467752-default.jpeg', name: 'XYZ Badar', type: 'IT/Software Services' },
    { icon: 'https://oneid.veevotech.com/org_dp/files/10467752-default.jpeg', name: 'XYZ Badar', type: 'IT/Software Services' },
    { icon: 'https://oneid.veevotech.com/org_dp/files/10467752-default.jpeg', name: 'XYZ Badar', type: 'IT/Software Services' },
    { icon: 'https://oneid.veevotech.com/org_dp/files/10467752-default.jpeg', name: 'XYZ Badar', type: 'IT/Software Services' },
    { icon: 'https://oneid.veevotech.com/org_dp/files/10467752-default.jpeg', name: 'XYZ Badar', type: 'IT/Software Services' },
    { icon: 'https://oneid.veevotech.com/org_dp/files/10467752-default.jpeg', name: 'XYZ Badar', type: 'IT/Software Services' },
    { icon: 'https://oneid.veevotech.com/org_dp/files/10467752-default.jpeg', name: 'XYZ Badar', type: 'IT/Software Services' },
    { icon: 'https://oneid.veevotech.com/org_dp/files/10467752-default.jpeg', name: 'XYZ Badar', type: 'IT/Software Services' },
    { icon: 'https://oneid.veevotech.com/org_dp/files/10467752-default.jpeg', name: 'XYZ Badar', type: 'IT/Software Services' },
    { icon: 'https://oneid.veevotech.com/org_dp/files/10467752-default.jpeg', name: 'XYZ Badar', type: 'IT/Software Services' },
    { icon: 'https://oneid.veevotech.com/org_dp/files/10467752-default.jpeg', name: 'XYZ Badar', type: 'IT/Software Services' },
    { icon: 'https://oneid.veevotech.com/org_dp/files/10467752-default.jpeg', name: 'XYZ Badar', type: 'IT/Software Services' },
    { icon: 'https://oneid.veevotech.com/org_dp/files/10467752-default.jpeg', name: 'XYZ Badar', type: 'IT/Software Services' },
    { icon: 'https://oneid.veevotech.com/org_dp/files/10467752-default.jpeg', name: 'XYZ Badar', type: 'IT/Software Services' },
    { icon: 'https://oneid.veevotech.com/org_dp/files/10467752-default.jpeg', name: 'XYZ Badar', type: 'IT/Software Services' },
    { icon: 'https://oneid.veevotech.com/org_dp/files/10467752-default.jpeg', name: 'XYZ Badar', type: 'IT/Software Services' },
    { icon: 'https://oneid.veevotech.com/org_dp/files/10467752-default.jpeg', name: 'XYZ Badar', type: 'IT/Software Services' },
    { icon: 'https://oneid.veevotech.com/org_dp/files/10467752-default.jpeg', name: 'XYZ Badar', type: 'IT/Software Services' },
    { icon: 'https://oneid.veevotech.com/org_dp/files/10467752-default.jpeg', name: 'XYZ Badar', type: 'IT/Software Services' },
    { icon: 'https://oneid.veevotech.com/org_dp/files/10467752-default.jpeg', name: 'XYZ Badar', type: 'IT/Software Services' },
    { icon: 'https://oneid.veevotech.com/org_dp/files/10467752-default.jpeg', name: 'XYZ Badar', type: 'IT/Software Services' },
    { icon: 'https://oneid.veevotech.com/org_dp/files/10467752-default.jpeg', name: 'XYZ Badar', type: 'IT/Software Services' },
    { icon: 'https://oneid.veevotech.com/org_dp/files/10467752-default.jpeg', name: 'XYZ Badar', type: 'IT/Software Services' },
    { icon: 'https://oneid.veevotech.com/org_dp/files/10467752-default.jpeg', name: 'XYZ Badar', type: 'IT/Software Services' },
    { icon: 'https://oneid.veevotech.com/org_dp/files/10467752-default.jpeg', name: 'XYZ Badar', type: 'IT/Software Services' },
    { icon: 'https://oneid.veevotech.com/org_dp/files/10467752-default.jpeg', name: 'XYZ Badar', type: 'IT/Software Services' },
    { icon: 'https://oneid.veevotech.com/org_dp/files/10467752-default.jpeg', name: 'XYZ Badar', type: 'IT/Software Services' },
    { icon: 'https://oneid.veevotech.com/org_dp/files/10467752-default.jpeg', name: 'XYZ Badar', type: 'IT/Software Services' },
    { icon: 'https://oneid.veevotech.com/org_dp/files/10467752-default.jpeg', name: 'XYZ Badar', type: 'IT/Software Services' },
    { icon: 'https://oneid.veevotech.com/org_dp/files/10467752-default.jpeg', name: 'XYZ Badar', type: 'IT/Software Services' },
]
export const forMeApps = [
    { icon: 'https://oneid.veevotech.com/frontend_assets/images/icons/smn.png?v=123', name: 'Hire 2.0', type: 'IT/Software Services', role: 'Admin' },
    { icon: 'https://oneid.veevotech.com/frontend_assets/images/icons/empleado.png?v=123', name: 'Empleado', type: 'Corporate App', description: 'Employe in Veevotech dfjd fdjfkdfjdlf dfj dlfjlfd', role: 'Admin' },
    { icon: 'https://oneid.veevotech.com/frontend_assets/images/icons/smn.png?v=123', name: 'Hire 2.0', type: 'IT/Software Services', role: 'Admin' },
    { icon: 'https://oneid.veevotech.com/frontend_assets/images/icons/empleado.png?v=123', name: 'Empleado', type: 'Corporate App', description: 'Employe in Veevotech', role: 'Admin' },
    { icon: 'https://oneid.veevotech.com/frontend_assets/images/icons/smn.png?v=123', name: 'Hire 2.0', type: 'IT/Software Services', role: 'Admin' },
    { icon: 'https://oneid.veevotech.com/frontend_assets/images/icons/empleado.png?v=123', name: 'Empleado', type: 'Corporate App', description: 'Employe in Veevotech', role: 'Admin' },
    { icon: 'https://oneid.veevotech.com/frontend_assets/images/icons/smn.png?v=123', name: 'Hire 2.0', type: 'IT/Software Services', role: 'Admin' },
    { icon: 'https://oneid.veevotech.com/frontend_assets/images/icons/empleado.png?v=123', name: 'Empleado', type: 'Corporate App', description: 'Employe in Veevotech', role: 'Admin' },
    { icon: 'https://oneid.veevotech.com/frontend_assets/images/icons/smn.png?v=123', name: 'Hire 2.0', type: 'IT/Software Services', role: 'Admin' },
    { icon: 'https://oneid.veevotech.com/frontend_assets/images/icons/empleado.png?v=123', name: 'Empleado', type: 'Corporate App', description: 'Employe in Veevotech', role: 'Admin' },
    { icon: 'https://oneid.veevotech.com/frontend_assets/images/icons/smn.png?v=123', name: 'Hire 2.0', type: 'IT/Software Services', role: 'Admin' },
    { icon: 'https://oneid.veevotech.com/frontend_assets/images/icons/empleado.png?v=123', name: 'Empleado', type: 'Corporate App', description: 'Employe in Veevotech', role: 'Admin' },
    { icon: 'https://oneid.veevotech.com/frontend_assets/images/icons/smn.png?v=123', name: 'Hire 2.0', type: 'IT/Software Services', role: 'Admin' },
    { icon: 'https://oneid.veevotech.com/frontend_assets/images/icons/empleado.png?v=123', name: 'Empleado', type: 'Corporate App', description: 'Employe in Veevotech', role: 'Admin' },
    { icon: 'https://oneid.veevotech.com/frontend_assets/images/icons/smn.png?v=123', name: 'Hire 2.0', type: 'IT/Software Services', role: 'Admin' },
    { icon: 'https://oneid.veevotech.com/frontend_assets/images/icons/empleado.png?v=123', name: 'Empleado', type: 'Corporate App', description: 'Employe in Veevotech', role: 'Admin' },
    { icon: 'https://oneid.veevotech.com/frontend_assets/images/icons/smn.png?v=123', name: 'Hire 2.0', type: 'IT/Software Services', role: 'Admin' },
    { icon: 'https://oneid.veevotech.com/frontend_assets/images/icons/empleado.png?v=123', name: 'Empleado', type: 'Corporate App', description: 'Employe in Veevotech', role: 'Admin' },
    { icon: 'https://oneid.veevotech.com/frontend_assets/images/icons/smn.png?v=123', name: 'Hire 2.0', type: 'IT/Software Services', role: 'Admin' },
    { icon: 'https://oneid.veevotech.com/frontend_assets/images/icons/empleado.png?v=123', name: 'Empleado', type: 'Corporate App', description: 'Employe in Veevotech', role: 'Admin' },
]

export const vtMarketApps = [
    { icon: 'https://oneid.veevotech.com/frontend_assets/images/icons/smn.png?v=123', name: 'Hire 2.0', description: 'IT/Software Services' },
    { icon: 'https://oneid.veevotech.com/frontend_assets/images/icons/smn.png?v=123', name: 'Hire 2.0', description: 'IT/Software Services' },
    { icon: 'https://oneid.veevotech.com/frontend_assets/images/icons/smn.png?v=123', name: 'Hire 2.0', description: 'IT/Software Services' },
    { icon: 'https://oneid.veevotech.com/frontend_assets/images/icons/smn.png?v=123', name: 'Hire 2.0', description: 'IT/Software Services' },
    { icon: 'https://oneid.veevotech.com/frontend_assets/images/icons/smn.png?v=123', name: 'Hire 2.0', description: 'IT/Software Services' },
    { icon: 'https://oneid.veevotech.com/frontend_assets/images/icons/smn.png?v=123', name: 'Hire 2.0', description: 'IT/Software Services' },
    { icon: 'https://oneid.veevotech.com/frontend_assets/images/icons/smn.png?v=123', name: 'Hire 2.0', description: 'IT/Software Services' },
    { icon: 'https://oneid.veevotech.com/frontend_assets/images/icons/smn.png?v=123', name: 'Hire 2.0', description: 'IT/Software Services' },
    { icon: 'https://oneid.veevotech.com/frontend_assets/images/icons/smn.png?v=123', name: 'Hire 2.0', description: 'IT/Software Services' },
    { icon: 'https://oneid.veevotech.com/frontend_assets/images/icons/smn.png?v=123', name: 'Hire 2.0', description: 'IT/Software Services' },
    { icon: 'https://oneid.veevotech.com/frontend_assets/images/icons/smn.png?v=123', name: 'Hire 2.0', description: 'IT/Software Services' },
    { icon: 'https://oneid.veevotech.com/frontend_assets/images/icons/smn.png?v=123', name: 'Hire 2.0', description: 'IT/Software Services' },
    { icon: 'https://oneid.veevotech.com/frontend_assets/images/icons/smn.png?v=123', name: 'Hire 2.0', description: 'IT/Software Services' },
    { icon: 'https://oneid.veevotech.com/frontend_assets/images/icons/smn.png?v=123', name: 'Hire 2.0', description: 'IT/Software Services' },
    { icon: 'https://oneid.veevotech.com/frontend_assets/images/icons/smn.png?v=123', name: 'Hire 2.0', description: 'IT/Software Services' },
    { icon: 'https://oneid.veevotech.com/frontend_assets/images/icons/smn.png?v=123', name: 'Hire 2.0', description: 'IT/Software Services' },
    { icon: 'https://oneid.veevotech.com/frontend_assets/images/icons/smn.png?v=123', name: 'Hire 2.0', description: 'IT/Software Services' },
    { icon: 'https://oneid.veevotech.com/frontend_assets/images/icons/smn.png?v=123', name: 'Hire 2.0', description: 'IT/Software Services' },
    { icon: 'https://oneid.veevotech.com/frontend_assets/images/icons/smn.png?v=123', name: 'Hire 2.0', description: 'IT/Software Services' },
    { icon: 'https://oneid.veevotech.com/frontend_assets/images/icons/smn.png?v=123', name: 'Hire 2.0', description: 'IT/Software Services' },
    { icon: 'https://oneid.veevotech.com/frontend_assets/images/icons/smn.png?v=123', name: 'Hire 2.0', description: 'IT/Software Services' },
    { icon: 'https://oneid.veevotech.com/frontend_assets/images/icons/smn.png?v=123', name: 'Hire 2.0', description: 'IT/Software Services' },
    { icon: 'https://oneid.veevotech.com/frontend_assets/images/icons/smn.png?v=123', name: 'Hire 2.0', description: 'IT/Software Services' },
    { icon: 'https://oneid.veevotech.com/frontend_assets/images/icons/smn.png?v=123', name: 'Hire 2.0', description: 'IT/Software Services' },
    { icon: 'https://oneid.veevotech.com/frontend_assets/images/icons/smn.png?v=123', name: 'Hire 2.0', description: 'IT/Software Services' },
    { icon: 'https://oneid.veevotech.com/frontend_assets/images/icons/smn.png?v=123', name: 'Hire 2.0', description: 'IT/Software Services' },
    { icon: 'https://oneid.veevotech.com/frontend_assets/images/icons/smn.png?v=123', name: 'Hire 2.0', description: 'IT/Software Services' },
    { icon: 'https://oneid.veevotech.com/frontend_assets/images/icons/smn.png?v=123', name: 'Hire 2.0', description: 'IT/Software Services' },
    { icon: 'https://oneid.veevotech.com/frontend_assets/images/icons/smn.png?v=123', name: 'Hire 2.0', description: 'IT/Software Services' },
    { icon: 'https://oneid.veevotech.com/frontend_assets/images/icons/smn.png?v=123', name: 'Hire 2.0', description: 'IT/Software Services' },
    { icon: 'https://oneid.veevotech.com/frontend_assets/images/icons/smn.png?v=123', name: 'Hire 2.0', description: 'IT/Software Services' },
    { icon: 'https://oneid.veevotech.com/frontend_assets/images/icons/smn.png?v=123', name: 'Hire 2.0', description: 'IT/Software Services' },
    { icon: 'https://oneid.veevotech.com/frontend_assets/images/icons/smn.png?v=123', name: 'Hire 2.0', description: 'IT/Software Services' },
    { icon: 'https://oneid.veevotech.com/frontend_assets/images/icons/smn.png?v=123', name: 'Hire 2.0', description: 'IT/Software Services' },
    { icon: 'https://oneid.veevotech.com/frontend_assets/images/icons/smn.png?v=123', name: 'Hire 2.0', description: 'IT/Software Services' },
    { icon: 'https://oneid.veevotech.com/frontend_assets/images/icons/smn.png?v=123', name: 'Hire 2.0', description: 'IT/Software Services' },
    { icon: 'https://oneid.veevotech.com/frontend_assets/images/icons/smn.png?v=123', name: 'Hire 2.0', description: 'IT/Software Services' },
    { icon: 'https://oneid.veevotech.com/frontend_assets/images/icons/smn.png?v=123', name: 'Hire 2.0', description: 'IT/Software Services' },
    { icon: 'https://oneid.veevotech.com/frontend_assets/images/icons/smn.png?v=123', name: 'Hire 2.0', description: 'IT/Software Services' },
    { icon: 'https://oneid.veevotech.com/frontend_assets/images/icons/smn.png?v=123', name: 'Hire 2.0', description: 'IT/Software Services' },
    { icon: 'https://oneid.veevotech.com/frontend_assets/images/icons/smn.png?v=123', name: 'Hire 2.0', description: 'IT/Software Services' },
    { icon: 'https://oneid.veevotech.com/frontend_assets/images/icons/smn.png?v=123', name: 'Hire 2.0', description: 'IT/Software Services' },
    { icon: 'https://oneid.veevotech.com/frontend_assets/images/icons/smn.png?v=123', name: 'Hire 2.0', description: 'IT/Software Services' },
    { icon: 'https://oneid.veevotech.com/frontend_assets/images/icons/smn.png?v=123', name: 'Hire 2.0', description: 'IT/Software Services' },
]

export const vtMarketAppsButtons = [
    { title: 'All', path: '/' },
    { title: 'Management', path: '/' },
    { title: 'Education', path: '/' },
    { title: 'Social Network', path: '/' },
    { title: 'IoT', path: '/' },
]